[project]
name = 'crowd_funding_app'
description = 'A secure, decentralized crowdfunding platform built on Stacks blockchain'
authors = ['Stacks Developer Team']
version = '1.0.0'
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.crowdfund]
path = 'contracts/crowdfund.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
